### PR TITLE
Adding Basic Tutorial (Linear Regression with MXNet)

### PR DESCRIPTION
**Pull request by karishmamalkan**

### CODE REVIEW

**Comment by mli** [comment]
can you please rename the file from `python/MXNet Basics.ipynb` to `python/tutorials/linear-regression.ipybn`. we can merge once it is done

**Comment by karishmamalkan** [comment]
I have updated the filename

**Comment by mli** [comment]
can you also delete `python/MXNet Basics.ipynb`

**Comment by karishmamalkan** [comment]
done

**Pull request merged**
