### PR TITLE
Updating to 0.94 api with python 3 compatibility 

### PR DESCRIPTION
**Pull request by ikvision**
The notebooks I fixed were with the Deprecated api that led to warnings

### CODE REVIEW

**Comment by mli** [comment]
can you please only commit the changes of the sources instead of all meta info and output results?

**Comment by ikvision** [comment]
Cleaned the outputs and added convergence graph for training mnist

**Comment by ikvision** [comment]
Hi, how did my last update look? Is there more I can do to make it acceptable?

**Comment by ikvision** [comment]
Following discussion moving the updated notebooks to:
[https://github.com/dmlc/mxnet/tree/master/docs/tutorials](url)
in markdown format

**Pull request closed without merging**
