### PR TITLE
Updating some notebooks that are hosted on mxnet.io

### PR DESCRIPTION
**Pull request by andremoeller**
Changes:
1. MNIST: removing the html / javascript that lets you draw in a box and classify since this notebook is hosted on the docs site, because attempting to classify throws a JS error -- IPython isn't a recognized name since the jupyter notebook server isn't running. This means I also had to rerun the entire notebook to make sure the cell execution numbers stay correct (rather than only the cell with the HTML and JS.

2. Matrix factorization: removed the LaTeX -- it shows up as unformatted on the docs site.

3. Predicting with imagenet: removed a useless cell that shows up as a big empty gray box on the site.

### CODE REVIEW

**Comment by andremoeller** [comment]
@mli 
Links to the changing pages:
http://mxnet.io/tutorials/python/matrix_factorization.html - fixing $k$ formatting
http://mxnet.io/tutorials/python/mnist.html - removing javascript drawing box
http://mxnet.io/tutorials/python/predict_imagenet.html - removing last python code box.

**Comment by mli** [comment]
can you just remove the js output but keep it on notebook?

**Comment by andremoeller** [comment]
I definitely could -- that would make the tutorial page on mxnet.io crowded and a little confusing since the code looks like:

html = """<style type="text/css">canvas { border: 1px solid black; }</style><div id="board"><canvas id="myCanvas" width="100px" height="100px">Sorry, your browser doesn't support canvas technology.</canvas><p><button id="classify" onclick="classify()">Classify</button><button id="clear" onclick="myClear()">Clear</button>Result: <input type="text" id="result_output" size="5" value=""></p></div>"""
script = """<script type="text/JavaScript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js?ver=1.4.2"></script><script type="text/javascript">function init() {var myCanvas = document.getElementById("myCanvas");var curColor = $('#selectColor option:selected').val();if(myCanvas){var isDown = false;var ctx = myCanvas.getContext("2d");var canvasX, canvasY;ctx.lineWidth = 8;$(myCanvas).mousedown(function(e){isDown = true;ctx.beginPath();var parentOffset = $(this).parent().offset(); canvasX = e.pageX - parentOffset.left;canvasY = e.pageY - parentOffset.top;ctx.moveTo(canvasX, canvasY);}).mousemove(function(e){if(isDown != false) {var parentOffset = $(this).parent().offset(); canvasX = e.pageX - parentOffset.left;canvasY = e.pageY - parentOffset.top;ctx.lineTo(canvasX, canvasY);ctx.strokeStyle = curColor;ctx.stroke();}}).mouseup(function(e){isDown = false;ctx.closePath();});}$('#selectColor').change(function () {curColor = $('#selectColor option:selected').val();});}init();function handle_output(out) {document.getElementById("result_output").value = out.content.data["text/plain"];}function classify() {var kernel = IPython.notebook.kernel;var myCanvas = document.getElementById("myCanvas");data = myCanvas.toDataURL('image/png');document.getElementById("result_output").value = "";kernel.execute("classify('" + data +"')",  { 'iopub' : {'output' : handle_output}}, {silent:false});}function myClear() {var myCanvas = document.getElementById("myCanvas");myCanvas.getContext("2d").clearRect(0, 0, myCanvas.width, myCanvas.height);}</script>"""
HTML(html+script)

======

I'm assuming that many more people will read the docs on the site than will run the tutorial notebook (by several orders of magnitude), so adding this code doesn't seem worth it to me, since it'll show up on the docs site.

Longer term, I think it would be best to have one branch in mxnet-notebooks for mxnet.io to clone from, then keep master for the notebooks themselves.

**Comment by mli** [comment]
i'm prefer to have a single branch. you can keep the scripts there, and don't generate the results. also add a comment that "this is for demo, you can skip it". or you can save the js on the file, and have a function to load iand run

**Comment by andremoeller** [comment]
Good idea -- moved these to another file, along with some mnist and lstm revisions.

**Comment by andremoeller** [comment]
Actually, just realized I forgot to take out the box -- don't merge yet (oops)

**Comment by andremoeller** [comment]
ok, should be good now. merge at your leisure.

**Pull request merged**
